--- Makefile
+++ Makefile
@@ -11,8 +11,6 @@ CMSISDAP         = $(DAPLINK)/daplink/cmsis-dap
 SRCS             = Src/main.c Src/stm32f1xx_it.c Src/stm32f1xx_hal_msp.c Src/system_stm32f1xx.c Src/usbd_conf.c Src/usbd_desc.c
 SRCS            += Src/usb/usbd.c Src/usb/hid/usbd_hid.c Src/usb/hid/usbd_hid_if.c Src/stm32f1xx_hal_pcd.c
 SRCS            += Src/usb/cdc/usbd_cdc_interface.c Src/usb/cdc/usbd_cdc.c Src/usb/i2c.c Src/usbd_ctlreq.c
-SRCS            += Src/mcp2515.cpp
-SRCS            += Src/usb/cdc/slcan.cpp
 SRCS            += $(CMSISDAP)/DAP.c $(CMSISDAP)/JTAG_DP.c $(CMSISDAP)/SW_DP.c
 
 SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c
@@ -27,13 +25,11 @@ SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dm
 SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c
 SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c
 SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c
-SRCS            += $(STM32SDK)/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c
 
 SRCS            += $(STM32SDK)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c
 SRCS            += $(STM32SDK)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c
 SRCS            += $(DAPLINK)/hic_hal/stm32/stm32f103xb/usb_config.c
 
-# Separate .s files to link weak symbols first
 SRCS_AS          = $(STM32SDK)/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xb.s
 
 LINK_SCRIPT      = $(STM32SDK)/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/linker/STM32F103XB_FLASH.ld
@@ -42,10 +38,10 @@ ELF              = $(OUTPUT_PATH)/$(TARGET_NAME).elf
 FW_BIN           = $(OUTPUT_PATH)/$(TARGET_NAME).bin
 MAP              = $(OUTPUT_PATH)/$(TARGET_NAME).map
 
-OBJS             = $(addprefix $(OUTPUT_PATH)/, $(SRCS:%=%.o))
-OBJS_AS          = $(addprefix $(OUTPUT_PATH)/, $(SRCS_AS:%=%.o))
-DEPS             = $(addprefix $(OUTPUT_PATH)/, $(SRCS:%=%.d))
-DEPS_AS          = $(addprefix $(OUTPUT_PATH)/, $(SRCS_AS:%=%.d))
+OBJS             = $(addprefix $(OUTPUT_PATH)/, $(SRCS:.c=.o))
+OBJS_AS          = $(addprefix $(OUTPUT_PATH)/, $(SRCS_AS:.s=.o))
+DEPS             = $(addprefix $(OUTPUT_PATH)/, $(SRCS:.c=.d))
+DEPS_AS          = $(addprefix $(OUTPUT_PATH)/, $(SRCS_AS:.s=.d))
 
 INC_PATH         = ./
 INC_PATH         = ./Inc
@@ -57,19 +53,15 @@ INC_PATH        += $(DAPLINK)/usb $(DAPLINK)/rtos
 
 CPUFLAGS         = -mthumb -mcpu=cortex-m3
 
-COMMON_FLAGS     = -Wall -Wextra
-COMMON_FLAGS    += -DSTM32F103xB -DHAL_TIM_MODULE_ENABLED
-COMMON_FLAGS    += -Wno-attributes
-COMMON_FLAGS    += -MD -g -Os -ffunction-sections -fdata-sections -fshort-wchar
-COMMON_FLAGS    += -flto
-COMMON_FLAGS    += -c $(CPUFLAGS)
-COMMON_FLAGS    += $(addprefix -I,$(INC_PATH))
-
-CFLAGS           = $(COMMON_FLAGS)
+CFLAGS           = -Wall -Wextra
+CFLAGS          += -DSTM32F103xB -DHAL_TIM_MODULE_ENABLED
+CFLAGS          += -Wno-attributes
+CFLAGS          += -MD -g -Os -ffunction-sections -fdata-sections -fshort-wchar
+CFLAGS          += -flto
+CFLAGS          += -c $(CPUFLAGS)
 CFLAGS          += -std=gnu99
-
-CXXFLAGS         = $(COMMON_FLAGS)
-CXXFLAGS        += -std=c++14
+CFLAGS          += -ffunction-sections -fdata-sections
+CFLAGS          += $(addprefix -I,$(INC_PATH))
 
 LDFLAGS          = -ggdb -Xlinker -Map=$(MAP) -T $(LINK_SCRIPT)
 LDFLAGS         += $(CPUFLAGS)
@@ -84,26 +76,21 @@ rebuild:
 	make clean
 	make all
 
-$(ELF): $(OBJS) $(OBJS_AS)
+$(ELF): $(OBJS) $(OBJS_CPP) $(OBJS_AS)
 	@echo "LD            $<"
-	@$(LD) $(LDFLAGS) $(OBJS_AS) $(OBJS) -o $(ELF)
+	@$(LD) $(LDFLAGS) $(OBJS_AS) $(OBJS_CPP) $(OBJS) -o $(ELF)
 
 $(FW_BIN): $(ELF)
 	@echo "OBJCOPY (bin) $@"
 	#@$(OBJCOPY) -j .text -j .data -j .ARM.extab -j .ARM.exidx -O binary $(ELF) $(FW_BIN)
 	@$(OBJCOPY) -O binary $(ELF) $(FW_BIN)
 
-$(OUTPUT_PATH)/%.c.o: %.c Makefile
+$(OUTPUT_PATH)/%.o: %.c Makefile
 	@[ -d $(dir $@) ] || mkdir -p $(dir $@)
 	@echo "CC            $<"
 	@$(CC) $(CFLAGS) $< -o $@
 
-$(OUTPUT_PATH)/%.cpp.o: %.cpp Makefile
-	@[ -d $(dir $@) ] || mkdir -p $(dir $@)
-	@echo "CXX            $<"
-	@$(CXX) $(CXXFLAGS) $< -o $@
-
-$(OUTPUT_PATH)/%.s.o: %.s Makefile
+$(OUTPUT_PATH)/%.o: %.s Makefile
 	@[ -d $(dir $@) ] || mkdir -p $(dir $@)
 	@echo "AS            $<"
 	@$(AS) $< -o $@
